FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/nginx-selfsigned.key -out /etc/ssl/nginx-selfsigned.crt \
            -subj "/C=FR/ST=FRANCE/L=MULHOUSE/O=42/OU=Unit/CN=localhost"

VOLUME /etc/hosts

EXPOSE 443

#useful

#docker run -d -v ${PWD}/hosts:/etc/hosts --name nginx1 -p 443:443 nginx1