version: '3.5'

services:
  nginx:
    container_name: nginx
    build: ./images/mariadb/.
    restart: always
    ports:
      - 443:443
    networks:
      - network
    volumes:
      - wordpress_v:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./images/mariadb/.
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: always
    env_file:
      - images/.env
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./images/wordpress/.
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - network

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      device: ./data/mariadb
      o: bind
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: ./data/wordpress
      o: bind

networks:
  network:
    driver: bridge