version: '3.5'

services:
  mariadb:
    container_name: mariadb
    build: ./images/mariadb/.
    ports:
      - "443:443"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./images/wordpress/.
    depends_on:
      - mariadb
    restart: always
    networks:
      - network

volumes:
  mariadb:

networks:
  network:
    driver: bridge