FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y mariadb-server mariadb-client
RUN mkdir -p /var/run/mysqld && \
    chown -R mysql:mysql /var/run/mysqld && \
    chmod 777 /var/run/mysqld

COPY 50-server.cnf /etc/mysql/mariadb.conf.d
COPY mariadb_script.sh /
COPY wordpress_data.sql /usr/local/bin/wordpress_data.sql

RUN chmod +x mariadb_script.sh

EXPOSE 3306

ENTRYPOINT [ "/mariadb_script.sh" ]

CMD ["mysqld", "--bind-address=0.0.0.0"]