services:
  nginx:
    container_name: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    build: ./nginx
    networks:
      - tor_network
    ports:
      - "5151:4242"
  tor:
    container_name: tor
    build: ./tor
    networks:
      - tor_network

networks:
  tor_network: