FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y mariadb-server mariadb-client

COPY ./50-server.cnf /etc/mysql/mariadb.conf.d

COPY ./mariadb_script.sh /
CMD ["mysqld", "--user=mysql", "--console"]
#CMD ["bash"]