FROM debian:bullseye

RUN apt-get update -y && \
    apt-get install -y mariadb-server mariadb-client

RUN mkdir -p /var/run/mysqld && \
    chown -R mysql:mysql /var/run/mysqld && \
    chmod 777 /var/run/mysqld

COPY ./50-server.cnf /etc/mysql/mariadb.conf.d

COPY mariadb_script.sh /

ENTRYPOINT [ "/mariadb_script.sh" ]